#!/bin/bash

used_space_before=$(df --output=used / | tail -n 1) # in KB

echo "=== Updating packages ==="
yay -Syu

echo "=== Removing caches ==="
yay -Scc

echo "=== Removing unused packages ==="
yay -Rsn $(yay -Qdtq) 

used_space_after=$(df --output=used / | tail -n 1) # in KB

echo "=== Stats ==="
used_space_current=$(echo "$used_space_after * 1024" | bc | numfmt --to=iec-i --suffix=B)
used_space_difference=$(echo "($used_space_after - $used_space_before) * 1024" | bc | numfmt --to=iec-i --suffix=B)
echo "- current used space: ${used_space_current}"
echo "- used space difference: ${used_space_difference}"
